"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-21 15:30:27.924188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('login_email', sa.String(length=255), nullable=False),
    sa.Column('partner_key', sa.String(length=64), nullable=True),
    sa.Column('user_key', sa.String(length=64), nullable=True),
    sa.Column('x_api_key_enc', sa.Text(), nullable=True),
    sa.Column('client_id', sa.String(length=128), nullable=True),
    sa.Column('client_secret_enc', sa.Text(), nullable=True),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partner_accounts')),
    sa.UniqueConstraint('partner_key', name=op.f('uq_partner_accounts_partner_key'))
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geebee_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=10), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('diff_maiden_name', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('nationality_iso', sa.String(length=3), nullable=True),
    sa.Column('birth_place', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_code', sa.String(length=6), nullable=True),
    sa.Column('mobile_no', sa.String(length=20), nullable=False),
    sa.Column('street_num', sa.String(length=255), nullable=True),
    sa.Column('additional_address', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('country_iso', sa.String(length=3), nullable=True),
    sa.Column('passport_num', sa.String(length=30), nullable=True),
    sa.Column('passport_issued_date', sa.Date(), nullable=True),
    sa.Column('passport_valid_upto', sa.Date(), nullable=True),
    sa.Column('passport_issue_place', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students'))
    )
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=False)
    op.create_index(op.f('ix_students_geebee_id'), 'students', ['geebee_id'], unique=True)
    op.create_index(op.f('ix_students_status'), 'students', ['status'], unique=False)
    op.create_table('blocked_account_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('partner_account_id', sa.Integer(), nullable=False),
    sa.Column('edubao_lead_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('current_step', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('app_type', sa.Integer(), nullable=True),
    sa.Column('expected_date_arrival', sa.Date(), nullable=True),
    sa.Column('blocked_acc_amt', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('blocked_acc_duration', sa.SmallInteger(), nullable=True),
    sa.Column('visa_eligibility_doc_type', sa.String(length=20), nullable=True),
    sa.Column('terms_accepted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partner_account_id'], ['partner_accounts.id'], name=op.f('fk_blocked_account_leads_partner_account_id_partner_accounts')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_blocked_account_leads_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blocked_account_leads')),
    sa.UniqueConstraint('account_id', name=op.f('uq_blocked_account_leads_account_id')),
    sa.UniqueConstraint('partner_account_id', 'edubao_lead_id', name=op.f('uq_blocked_account_leads_partner_account_id'))
    )
    op.create_index(op.f('ix_blocked_account_leads_partner_account_id'), 'blocked_account_leads', ['partner_account_id'], unique=False)
    op.create_index(op.f('ix_blocked_account_leads_status'), 'blocked_account_leads', ['status'], unique=False)
    op.create_index(op.f('ix_blocked_account_leads_student_id'), 'blocked_account_leads', ['student_id'], unique=False)
    op.create_table('edubao_call_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_account_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('request_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partner_account_id'], ['partner_accounts.id'], name=op.f('fk_edubao_call_log_partner_account_id_partner_accounts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edubao_call_log'))
    )
    op.create_index(op.f('ix_edubao_call_log_created_at'), 'edubao_call_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_edubao_call_log_partner_account_id'), 'edubao_call_log', ['partner_account_id'], unique=False)
    op.create_table('form_reference_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_account_id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['partner_account_id'], ['partner_accounts.id'], name=op.f('fk_form_reference_cache_partner_account_id_partner_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_form_reference_cache')),
    sa.UniqueConstraint('partner_account_id', name=op.f('uq_form_reference_cache_partner_account_id'))
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('edubao_doc_id', sa.Integer(), nullable=True),
    sa.Column('doc_key', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('original_file_name', sa.String(length=255), nullable=False),
    sa.Column('mimetype', sa.String(length=100), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['blocked_account_leads.id'], name=op.f('fk_documents_lead_id_blocked_account_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_lead_id'), 'documents', ['lead_id'], unique=False)
    op.create_table('lead_step_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.SmallInteger(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['blocked_account_leads.id'], name=op.f('fk_lead_step_submissions_lead_id_blocked_account_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_step_submissions'))
    )
    op.create_index(op.f('ix_lead_step_submissions_lead_id'), 'lead_step_submissions', ['lead_id'], unique=False)
    op.create_table('payers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('edubao_payer_id', sa.Integer(), nullable=True),
    sa.Column('payer_account_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=10), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_code', sa.String(length=6), nullable=True),
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('relationship_to_student', sa.String(length=50), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('nationality_iso', sa.String(length=3), nullable=True),
    sa.Column('birth_place', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('street_num', sa.String(length=255), nullable=True),
    sa.Column('additional_address', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('country_iso', sa.String(length=3), nullable=True),
    sa.Column('transfer_amt', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['blocked_account_leads.id'], name=op.f('fk_payers_lead_id_blocked_account_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payers'))
    )
    op.create_index(op.f('ix_payers_lead_id'), 'payers', ['lead_id'], unique=False)
    op.create_table('verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('result', sa.String(length=30), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_verifications_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['blocked_account_leads.id'], name=op.f('fk_verifications_lead_id_blocked_account_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verifications'))
    )
    op.create_index(op.f('ix_verifications_lead_id'), 'verifications', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verifications_lead_id'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_index(op.f('ix_payers_lead_id'), table_name='payers')
    op.drop_table('payers')
    op.drop_index(op.f('ix_lead_step_submissions_lead_id'), table_name='lead_step_submissions')
    op.drop_table('lead_step_submissions')
    op.drop_index(op.f('ix_documents_lead_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('form_reference_cache')
    op.drop_index(op.f('ix_edubao_call_log_partner_account_id'), table_name='edubao_call_log')
    op.drop_index(op.f('ix_edubao_call_log_created_at'), table_name='edubao_call_log')
    op.drop_table('edubao_call_log')
    op.drop_index(op.f('ix_blocked_account_leads_student_id'), table_name='blocked_account_leads')
    op.drop_index(op.f('ix_blocked_account_leads_status'), table_name='blocked_account_leads')
    op.drop_index(op.f('ix_blocked_account_leads_partner_account_id'), table_name='blocked_account_leads')
    op.drop_table('blocked_account_leads')
    op.drop_index(op.f('ix_students_status'), table_name='students')
    op.drop_index(op.f('ix_students_geebee_id'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_table('students')
    op.drop_table('partner_accounts')
    # ### end Alembic commands ###
